//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebDocSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAODICH_MUAVIP
    {
        public string maKH { get; set; }
        public System.DateTime thoiGian { get; set; }
        public decimal giaVIP { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
