//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebDocSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.GIAODICH_MUASACH = new HashSet<GIAODICH_MUASACH>();
            this.GIAODICH_MUAVIP = new HashSet<GIAODICH_MUAVIP>();
        }

        [DisplayName("Mã khách hàng")]
        public string maKH { get; set; }
        [DisplayName("Tên khách hàng")]
        [Required(ErrorMessage = "*")]
        public string tenKH { get; set; }
        [DisplayName("Ảnh đại diện")]
        public string avatar { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "*")]
        [EmailAddress]
        public string email { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "*")]
        public string matKhau { get; set; }
        [DisplayName("VIP")]
        [Required(ErrorMessage = "*")]
        public bool isVIP { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAODICH_MUASACH> GIAODICH_MUASACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAODICH_MUAVIP> GIAODICH_MUAVIP { get; set; }
    }
}
