//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebDocSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [DisplayName("Mã nhân viên")]
        public string maNV { get; set; }
        [DisplayName("Tên nhân viên")]
        [Required(ErrorMessage = "*")]
        public string tenNV { get; set; }
        [DisplayName("Ảnh đại diện")]
        public string avatar { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "*")]
        [EmailAddress]
        public string email { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "*")]
        public string matKhau { get; set; }
        [DisplayName("Admin")]
        [Required(ErrorMessage = "*")]
        public bool isAdmin { get; set; }
    }
}
