//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebDocSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.GIAODICH_MUASACH = new HashSet<GIAODICH_MUASACH>();
            this.NOIDUNGSACHes = new HashSet<NOIDUNGSACH>();
        }

        [DisplayName("Mã sách")]
        public string maSach { get; set; }
        [DisplayName("Tên sách")]
        [Required(ErrorMessage = "*")]
        public string tenSach { get; set; }
        [DisplayName("Ảnh bìa")]
        public string anhBia { get; set; }
        [DisplayName("Tác giả")]
        [Required(ErrorMessage = "*")]
        public string tacgia { get; set; }
        [DisplayName("Loại sách")]
        [Required(ErrorMessage = "*")]
        public int loai { get; set; }
        [DisplayName("Giá")]
        [Required(ErrorMessage = "*")]
        [Range(0, int.MaxValue, ErrorMessage = "Giá trị phải lớn hơn hoặc bằng 0")]
        public decimal gia { get; set; }
        [DisplayName("Năm xuất bản")]
        [Required(ErrorMessage = "*")]
        public int namXuatBan { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "*")]
        [DataType(DataType.MultilineText)]
        public string moTa { get; set; }
        [DisplayName("Thể loại")]
        [Required(ErrorMessage = "*")]
        public string maTheLoai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAODICH_MUASACH> GIAODICH_MUASACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIDUNGSACH> NOIDUNGSACHes { get; set; }
        public virtual THELOAI THELOAI { get; set; }
        public virtual SACH_LUOTXEM SACH_LUOTXEM { get; set; }
    }
}
