//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebDocSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH_LUOTXEM
    {
        public string maSach { get; set; }
        public long soLuotXem { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
