//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebDocSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public string maTS { get; set; }
        public string tenTS { get; set; }
        public string dvt { get; set; }
        public int giaTri { get; set; }
        public bool tinhTrang { get; set; }
    }
}
